//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fry_Article
    {
        public int Id { get; set; }
        public Nullable<int> TagId { get; set; }
        public string Tag { get; set; }
        public string Source { get; set; }
        public string Title { get; set; }
        public string Abstract { get; set; }
        public string BaiduUrl { get; set; }
        public string RealUrl { get; set; }
        public string Domain { get; set; }
        public Nullable<byte> IsVerify { get; set; }
        public string PageContext { get; set; }
        public string Author { get; set; }
        public string PulDate { get; set; }
        public string Title_ { get; set; }
        public string Type_ { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
